### ISSUE TITLE
Funzionalità del sito

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#1]
Funzionalità del sito candidate per l'implementazione:
-Per ogni artista la sua biografia e gli album con le canzoni pubblicate
-Lista delle canzoni con rispettivo testo (più link di youtube)
-Ricerca per canzone, aritsta, album
-Possibilità di pubblicare articoli-news con possibilità di commentare
-Possibilità di registrazione al sito con funzionalità di salvare canzoni preferite
-Gestione dei gradi degli iscritti con possiblità di assegnazione privilegi
-Ogni amministratore ha la possiblità di aggiungere artisti, album e canzoni
-Per ogni canzone indice di gradimento disponibile per utenti registrati

Aggiuntive:
-Pagina dinamica di canzoni con maggior indice di gradimento (tipo classifica), le ultime inserite, il cantante più piaciuto.

**Comment by korut94** [comment]
Accessibilità:
+Menu di navigazione circolare dispositivi mobile

**Comment by Polpetta** [comment]
Metto il link del pie menu' che ho trovato in caso volessimo riutilizzare il codice:
https://github.com/Nikesh/Pie-Menu
