### ISSUE TITLE
Troppo poca separazione di elementi nella homepage

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#101]
Nella homepage si ha poca separazione tra "ultime news" "ultime canzoni". Da aumentare un pochetto lo spazio.
Screenshot in allegato (succede cosi' per tutti i browser, non solo Opera)
![immagine](https://cloud.githubusercontent.com/assets/5928183/12818978/5d513b5a-cb59-11e5-8fd1-e2f627096465.png)

**Comment by WeissL** [comment]
Fatto

**Comment by Polpetta** [comment]
@WeissL Tra 5 minuti ti dico se va bene o no!! 😊👍 Tempo che si aggiorni il sito

**Comment by Polpetta** [comment]
Ottimo cosi'!
