### ISSUE TITLE
Spostare sezioni in relazione

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#103]
la relazione **deve** contenere in prima pagina: 
- [x] eventuali password degli utenti da utilizzare in fase di correzione (una coppia login-passwd per ogni classe di utenza);
- [x] indirizzo email del referente del gruppo per eventuali comunicazioni.

**Comment by Polpetta** [comment]
Per la prima ci siamo, la seconda la aggiungo appena accendo il PC
Il 05 feb 2016 08:01, "massi94" notifications@github.com ha scritto:
