### ISSUE TITLE
Implementazione indice gradimento per canzoni, album e articoli

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#11]
Come pensavamo di implementarlo?

**Comment by Polpetta** [comment]
Sposto nella Milestone XML - Database perchè è un lavoro implementativo di @massi94

**Comment by massi94** [comment]
Per la valutazione delle canzoni, per ogni utente registrato ci sarà un elemento "votes" che conterrà la lista delle canzoni a cui ha espresso una preferenza. Questa lista è composta da un insieme di elementi "typeVote" che hanno come attributo °rifer" l'id della canzone, e contengono +1 o -1 a seconda se la valutazione è positiva o negativa

**Comment by Polpetta** [comment]
:+1:

**Comment by massi94** [comment]
Teniamo solo l'indice di gradimento per le canzoni, aggiungo un elemento grade che è la somma dei +1, -1 voti espressi fino a quel momento

**Comment by Polpetta** [comment]
Ok. Viene tenuto conto anche di chi vota o gli utenti possono votare piu' volte?

**Comment by massi94** [comment]
possono votare solo gli utenti registrati, e ogni voto viene salvato in memoria, quindi non è possibile votare più volte.

**Comment by Polpetta** [comment]
Ottimo. Quindi bisogna che la votazione sia visibile solamente quando un utente e' loggato o lasciamo la votazione visibile ma impediamo a un utente non loggato di votare?
Dipende anche da come @korut94 vuole implementare le sessioni utente.

**Comment by massi94** [comment]
secondo me si puo' anche lasciare visibile e impedire a un non loggato di votare!

**Comment by korut94** [comment]
@Polpetta Io impedirei la votazione da parte di un utente non loggato. Altrimenti uno può mandare in overflow il contatore abbastanza in fretta.

**Comment by Polpetta** [comment]
@massi94 come fanno la maggioranza dei siti
@korut94  fare quello che @massi94 ha detto e' fattibile lato server?

**Comment by korut94** [comment]
Si non ci dovrebbero essere problemi. Faccio un controllo e se è loggato inserisco il pulsante di votazione positiva e negaritava altrimenti viene visualizzato solo il risultato.

**Comment by Polpetta** [comment]
@korut94 Ok. Quindi se e' tutto risolto direi che possiamo chiudere questa issue 😊
