### ISSUE TITLE
Pagina search non funzionante

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#14]
Alla richiesta di visualizzazione dei risultati di ricerca per testarne la visualizzazione mi viene segnato che non viene trovata (404).

L'indirizzo della pagina è: http://tecnologie-web.studenti.math.unipd.it/tecweb/~amantova/cgi-bin/r.cgi?section=search

Errore riscontrato:

```
Software error:

Error 404: page not found! at r.cgi line 51.

For help, please send mail to the webmaster (webmaster@localhost), giving this error message and the time and date of the error.


```

La pagina servita dovrebbe essere [search.html](https://github.com/Hexamini/PassioneKaraoke/blob/HTMLDev/data/views/search.html)

**Comment by korut94** [comment]
Buon Natale!

**Comment by Polpetta** [comment]
@korut94 Grazie anche a te!🎅
