### ISSUE TITLE
Specificare query string di ogni pagina

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#15]
Oltre alla parte _section_ alcune pagine richiedono delle specifiche ulteriori, come ad esempio: nome cantante, album, metodo d'accesso ( inserimento o modifica ), etc. 
Per ogni pagine comporre la query string inserendo 
_name_value=value_
 usando la & per separare le variabili.

**Comment by Polpetta** [comment]
Specificami le pagine.

@massi94 mi sa che centri anche te.

**Comment by korut94** [comment]
AlbumManager
ArticleManager
Article
Articles
Artist
Artists
Index
Login
Signin
SongDescription
SongManager
UserPage

**Comment by Polpetta** [comment]
@korut94 Ok.
@massi94 dobbiamo definire un elenco delle keyword!

**Comment by Polpetta** [comment]
Dopo una discussione, ci si accordati per l'identificazione degli argomenti tramite l'utilizzo della primary key. Questo implica che ogni elemento in una pagina web deve avere una PK univoca.
