### ISSUE TITLE
Pulsanti mancanti in pagina artists

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#17]
Che pulsanti servono sulla pagina artists? c'è un commento che dice che dipendono dallo status dell'account, ma non trovo nessuna referenza a quei pulsanti

**Comment by Polpetta** [comment]
Dici questo spezzone di codice?

``` html
<div class="artist-option">
        <!-- Campo vuoto per gestione in base al login -->
</div>
```

**Comment by Polpetta** [comment]
In ogni caso questo serviva perche' si pensava che con Javascript questo div venisse riempito con dei bottoni in caso l'utente fosse loggato (tipo con il simbolo dell'aggiunta della canzone ai preferiti o la modifica della canzone per l'amministratore)

**Comment by WeissL** [comment]
I bottoni da fare sono già stati scelti? che intanto potrei predisporre le icone, così poi rimarrebbe solamente il link con JS

**Comment by Polpetta** [comment]
@WeissL I bottoni non sono stati scelti!:) mi sembra

**Comment by Polpetta** [comment]
Confermo che lo spazio è stato lasciato appositamente per poter riempire in futuro (non sono ancora presenti le immagini) con dei bottoni per poter permettere la modifica dell'artista.

Chiudo la issue in quanto la risposta è stata data.
