### ISSUE TITLE
Descrizione manca su articoli, nella lista

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#18]
Manca la descrizione degli articoli, che è richiesta dal file artilceList, mentre nelle voci article non trovo nessun riferimento a descrizioni... posso aggiungerla? se si con  che vocabolo è stato segnato?

**Comment by Polpetta** [comment]
@massi94 risulta tua la pagina a cui si sta riferendo! Ti ho messo come intestatario.
@WeissL si occupa fabio della risoluzione, digli solo cosa c'e' che non va bene! :blush:

**Comment by massi94** [comment]
@WeissL Ma si articleList vengono richiesti title e subtitle, che ci sono su article

**Comment by WeissL** [comment]
@massi94 ma non dovrei avere una piccola preview quando apro l'articolo?

**Comment by Polpetta** [comment]
@WeissL In che senso? :blush:

**Comment by Polpetta** [comment]
@WeissL Cosa intendevi te per preview?

**Comment by WeissL** [comment]
@Polpetta mi sembrava una volta ci fossero due righe di introduzione all'articolo, ma Andrea mi aveva detto alla fine che questa cosa non si era messa non mi ricordo più il motivo ma era una cosa ragionata. Chiudo l'issue vista la risposta

**Comment by Polpetta** [comment]
@WeissL Ok
