### ISSUE TITLE
Struttura delle pagine html

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#2]
Apro questo threead per chiedere chiarimenti su come dovranno essere strutturate le pagine web con le "nostre" keyword.
Invoco @korut94 per ulteriori chiarimenti. In page.html quindi che  _cosa_ ci dovrà andare?

EDIT: tutti i cambi di assegnazione che vedete sotto è perchè ho cercato di assegnare me e @korut94 a questo problema insieme ma evidentemente non si può.

**Comment by WeissL** [comment]
Io direi:
Modulo header e modulo fotter da poter richiamare all'interno di qualsiasi pagina,
Una pagina per ogni sezione base
Una cartella views per tutti i moduli templatizzati

**Comment by Polpetta** [comment]
Ok, ma se mettiamo un modulo header significa che tutti i meta finiscono nel database. Questo non lo fa diventare troppo pesante dopo? È questa la mia "paura".
Comunque al commit [831643e](https://github.com/Hexamini/PassioneKaraoke/commit/831643e0a3695e07c7cbbed7fd9565a1c6ca7152) potete vedere un esempio di file generico "page.html", che è incompleto e vedo di completare appena posso.

**Comment by korut94** [comment]
Allora, la base da partire è la page.html che deve essere cosi:

``` html
!DOCTYPE <!-- completatelo -->
<html>
 <head>
  <title> !_title_! </title>
  !_listMeta_! <!-- lista di meta -->
 </head>
 <body>
   !_content_! <!-- qui si metta l'oggetto della pagina -->
  <div class="footer">
    Scritto fatto dai quattro pirla
  </div>  
 </body>
</html>
```

I meta non saranno nel database ma ben si nell'oggetto della pagina. Voi dovete fare l'article ad esempio, bene, allora io faro Object::Article::getMeta() e non dovrò in alcun modo interrogare il DB. Da qui si può o scrivere i meta sul metodo o sul database.

**Comment by Polpetta** [comment]
> I meta non saranno nel database ma ben si nell'oggetto della pagina
> [...]
> Da qui si può o scrivere i meta sul metodo o sul database.

Non riesco a capire bene sto discorso. Quindi la pagina article.html per esempio avrà la sua definizione dei meta che a sua volta ci saranno delle keyword all'interno che saranno pescate dal DB?

**Comment by korut94** [comment]
Si possono mettere le meta sul database, sul metodo oppure su un file. Quale preferite?
Se lo fate su file per ogni pagina dovete fare un file con i meta. Io lo sconsiglierei perché i meta sono proprietà della pagina e non ha senso promuovere ad oggetto.

**Comment by Polpetta** [comment]
Bene, direi che alla fine è stata adottata la seconda soluzione, quindi questa issue la posso chiudere in quanto il problema non sussiste più!
