### ISSUE TITLE
Aggiungere visualizzazione gradimento della canzone

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#21]
Vista l'implementazione dell'indice di gradimento per le canzoni, bisogna aggiungere la visualizzazione del totale dei voti espressi per ogni canzone, e la possibilità di cliccare su "mi piace" o "non mi piace"

**Comment by Polpetta** [comment]
Ok. Le immagini per il "mi piace" e "non mi piace" sono pronte? Se si @massi94 le puoi caricare? Vanno messe nel CSS o le posso mettere direttamente io nell'HTML @WeissL?

**Comment by massi94** [comment]
Ho fatto una bozza per i "mi piace" e "non mi piace" c'è una dimensione particolare, o un formato particolare @WeissL ? E dove devo caricarle?

**Comment by WeissL** [comment]
i tasti sarebbe meglio farli in svg in modo da poterli apliare a piacere senza dover rifare l'immagine

**Comment by Polpetta** [comment]
@massi94 Carica i tasti e chiudi la issue
