### ISSUE TITLE
Rimuovere la select dell'artist in albumManager.html

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#23]
La selezione dell'artista viene fatta prima di entrare in quelle sezione. Togliere la select e sostituirla con un div per poter visualizzare quale artista è stato scelto.

**Comment by massi94** [comment]
@korut94 Ma se si vuole inserire un nuovo album dalla pagina amministratore, bisognerà indicare a quale artista si riferisce

**Comment by Polpetta** [comment]
@massi94 L'avevo lasiciato proprio per questo motivo

**Comment by korut94** [comment]
Ah ok!

**Comment by Polpetta** [comment]
Chiudo allora
