### ISSUE TITLE
Merge manuale non completo

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#24]
Merge di file in conflitto tra loro non risolto, da risolvere in data/views/index.html

**Comment by WeissL** [comment]
mmmm, non ricordo di aver toccato niente... sicuramente sistemo... come avevo già detto finirò il 26 tutto il css, anche parte mobile, e poi darò anche un'occhiata di nuovo se tutto è apposto su html

**Comment by korut94** [comment]
@WeissL Grandioso!

**Comment by Polpetta** [comment]
@WeissL Ok. Appena risolvi questo conflitto chiudi la issue.
