### ISSUE TITLE
Proposta per search

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#25]
Si riesce a mettere al posto del numero di elementi trovati nella ricerca una cosa del tipo:

<h1>Stai cercando: [%parola cercata %]</h1>

<h2>Elementi trovati: [%numero elementi %]</h2>

**Comment by Polpetta** [comment]
Devi chiedere a @korut94

**Comment by korut94** [comment]
Si certo, ma ti consiglio di non perderci tempo essendo che sarà una cosa, a mio parere, da valutare se scartarla.

**Comment by Polpetta** [comment]
@korut94 Ok, ma ci devi dare un parere tuo di quanto tempo ti porterebbe via farlo perche' i risultati arrivano sempre da perl! 😅

**Comment by korut94** [comment]
Ti direi anche tre giorni per certezza ma essendo che non è l'unica cosa da fare non mi fido troppo ad assicurarvi che ho tempo per farla.

**Comment by Polpetta** [comment]
Ok, allora la teniamo aperta per ultima.

**Comment by Polpetta** [comment]
@korut94 Alla fine quindi questa cosa la implementiamo o no?

**Comment by korut94** [comment]
Direi di no per motivi di tempo e vero valore aggiunto al progetto.
