### ISSUE TITLE
Aggiungere nella view login.html una sezione d'errore

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#26]
Nel caso la registrazione fallisse nella view login.html dovrebbe apparire una sezione con il messaggio d'errore. Consiglierei di creare un div con un id o classe che possa settare nel perl da rendere visibile o nascondere il messaggio d'errore. Esempio:

``` html
<div class="[% visible %]">
 Errore nel login, username o password errate.
</div>
```

**Comment by Polpetta** [comment]
Non sono io l'assegnatario, chi ha scritto le pagine lo trovi nel TODO.

**Comment by korut94** [comment]
Ma @massi94 dovrebbe essere impegnato con l'xml. Te sei in attesa, non ho visto codice javascript.

**Comment by massi94** [comment]
Per la segnalazione di un errore durante l'inserimento dati in una form non è buona norma segnalarlo in generale come proposto da @korut94 perchè non è preciso, e scriverlo in testa o coda della form provoca disorientamento, la soluzione proposta dalla prof è che il messaggio di errore viene visualizzato via javascript (che dovrebbe essere il tema della prossima lezione di laboratorio)

**Comment by korut94** [comment]
La segnalazione come dice @massi94 è valida fino a che i controlli posso essere eseguiti lato client. Nel caso della login i dati posso essere validi ma non presente nel server. In quel caso l'unica soluzione è avvertirlo successivamente con un messaggio d'errore generico per questioni di sicurezza.

**Comment by massi94** [comment]
Allora procedo all'inserimento del messaggio di errore, nel caso della issue #27 i controlli si che vanno fatti via javascript, perchè richiedono solo la verifica della consistenza dei dati

**Comment by Polpetta** [comment]
@korut94 Non è possibile che JavaScript effettui una richiesta al server che gli conferma l'esistenza meno dei dati? In questo caso la pagina non dovrebbe ricaricarsi. In caso JavaScript non sia presente/funzionante verrà eseguita una degradazione in cui la form viene direttamente inviata al server che risponde con un'altra pagina (tipo il classico login con linguaggi lato server)

**Comment by korut94** [comment]
Non so se esista. Sono propenso a dirti che c'è ma non vedo l'utilità.

**Comment by Polpetta** [comment]
@korut94 Perche'?

**Comment by korut94** [comment]
Comunque dovresti chiamare uno script Perl e dovresti ricevere la risposta.

**Comment by Polpetta** [comment]
@korut94 Si, ma eviterebbe il refresh della pagina, migliorandone l'usabilità. Secondo me è un punto che dobbiamo studiare bene, o chiedere consiglio alla professoressa.

**Comment by korut94** [comment]
@Polpetta Per me diventa solo più complicato e non c'è un vero guadagno.

**Comment by Polpetta** [comment]
@korut94 Non so, è che in JavaScript abbiamo "solo" controlli su form, e non vorrei che fossimo penalizzati per questo!
