### ISSUE TITLE
Username elemento o attributo

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#28]
Nel database userlist.xml, sarà l'username a identificare l'user. Bisogna scegliere se verrà messo come elemento o come attributo, ma non tutte e due contemporaneamente.

**Comment by massi94** [comment]
Direi di tenere l'attributo per essere conformi con gli altri identificatori, correggo!

**Comment by korut94** [comment]
@massi94 Ottima scelta direi!
