### ISSUE TITLE
categoryManager non trovato

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#35]
Andando all'indirizzo

```
/~amantova/cgi-bin/r.cgi?section=categoryManager
```

Si ottiene un 404. Da sistemare

**NOTA**: una volta chiusa questa issue aprirne una con label _todo_ con me come assegnatario per verificarne la compilazione

**Comment by korut94** [comment]
Ma davvero vi serve una pagina CategoryManager assestante?

**Comment by korut94** [comment]
Comunque ho creato la pagina, se la volete togliere create una nuova issue.

**Comment by Polpetta** [comment]
@korut94 Ma la pagina .html non era già presente?

**Comment by korut94** [comment]
Si ma quella view va negli strumenti dell'amministratore. Per me una sezione per l'inserimento delle categorie non è utile.
