### ISSUE TITLE
Colori dei microfoni

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#39]
Ricordarsi di verificare se i colori dei microfoni "mi piace" e "non mi piace" sono accessibili anche per chi ha problemi visivi in quanto sono verdi e rossi

Mi riferisco a:
- ![Microfono mi piace](https://github.com/Hexamini/PassioneKaraoke/blob/ecca2bb79b7cfa5b97d98bd542f0712b49e48a85/data/img/like.svg)
- ![Microfono non mi piace](https://github.com/Hexamini/PassioneKaraoke/blob/ecca2bb79b7cfa5b97d98bd542f0712b49e48a85/data/img/unlike.svg)

**Comment by Polpetta** [comment]
@massi94 mi puoi caricare le immagini di tutti i test? Che così poi le teniamo per aggiungerle nella relazione.

**Comment by massi94** [comment]
Immagine originale:
![origlikeblue](https://cloud.githubusercontent.com/assets/7117763/12117694/be296cf8-b3c2-11e5-93a4-b57f1fb0c8cc.jpg)
![origunlike](https://cloud.githubusercontent.com/assets/7117763/12117695/be29c108-b3c2-11e5-84f8-a5c523989364.jpg)

Microfono Blu:
Deuteranope
![deu_likeblu](https://cloud.githubusercontent.com/assets/7117763/12117715/d5c1ce28-b3c2-11e5-950e-703b6237a77b.jpg)
Protanope
![pro_likeblu](https://cloud.githubusercontent.com/assets/7117763/12117717/d5caacf0-b3c2-11e5-8331-8b48e36bc8c1.jpg)
Tritanope
![tri_likeblu](https://cloud.githubusercontent.com/assets/7117763/12117716/d5c499f0-b3c2-11e5-9763-c9b535ca3fb4.jpg)

Microfono Rosso:
Deuteranope
![deu_unlike](https://cloud.githubusercontent.com/assets/7117763/12117730/e878ee34-b3c2-11e5-9fcc-92420a089583.jpg)
Protanope
![pro_unlike](https://cloud.githubusercontent.com/assets/7117763/12117731/e8a3ab7e-b3c2-11e5-9605-3516fd65016b.jpg)
Tritanope
![tri_unlike](https://cloud.githubusercontent.com/assets/7117763/12117732/e8a62f16-b3c2-11e5-963e-e83c44775722.jpg)

**Comment by Polpetta** [comment]
Ok, va segnato nella relazione che è stato tolto il microfono verde in quanto subiva una variazione troppo alta del suo aspetto, e quindi è stato cambiato con il blu.

Questa issue si riferisce all'accessibilità #43

**Comment by Polpetta** [comment]
@massi94 Questa issue possiamo chiuderla? I colori adesso vanno bene?

**Comment by massi94** [comment]
@Polpetta Adesso visivamente sono ben distinguibili, c'è comunque il problema di veicolare l'informazione attraverso i colori!

**Comment by Polpetta** [comment]
@massi94 Ok, allora lasciamola aperta.

**Comment by Polpetta** [comment]
@massi94 riguardo al problema di veicolare l'informazione attraverso i colori che cosa facciamo? :blush:

**Comment by WeissL** [comment]
@Polpetta @massi94 essendo l'informazione non veicolata solamente dal colore sencodo me alla fine sono accettabili? che dite? alla fine anche la forma del microfono implica una certa azione

**Comment by Polpetta** [comment]
@WeissL Io aspetterei la conferma di @massi94, alla fine ha fatto lui i bottoni. Piu' che altro "riesumevo" la issue in quanto mi serviva sapere che cosa era  stato deciso in quanto devo scriverlo nella relazione, o non finiamo piu' 😅

**Comment by Polpetta** [comment]
@massi94 Io ho messo nella relazione intanto le immagini che hai mandato qui. Poi vogliamo argomentare anche la storia che i colori secondo noi veicolano abbastanza?

**Comment by massi94** [comment]
@Polpetta Mi sono perso, abbiano usato alla fine i bottoni quelli con l'etichetta con scritto "mi piace" o quelli normali? Perché basterebbe solo un accenno, o neanche, visto che non si presenterebbe più il problema del colore!

**Comment by Polpetta** [comment]
@massi94 A me sembra che abbiamo usati quelli senza la scritta! A me non cambia nulla, mi basta tu e luca vi decidiate e che facciate i test sull'accessibilità relative alle nuove immagini, se adottiamo quelle. Ho scritto la relazione in maniela tale che basta sovrascrivere le immagini senza toccare nulla :D
