### ISSUE TITLE
Sezioni senza titoli

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#4]
I file delle sezioni, come 'artists' ed altri, non hanno il meta titolo. Da aggiungere.

**Comment by Polpetta** [comment]
Meta titolo?

**Comment by korut94** [comment]
@title tra i campi meta nei file html. Se non c'è quando visualizzerò la pagina verrà " - Passione Karaoke".

**Comment by Polpetta** [comment]
Si ma nota che alcune pagine sono solo dei "pezzi" per la creazione di 
altre, rer questo non ho inserito nulla.

Invece in altre mi sono proprio dimenticato, provvedo a correggere.

Il 02/12/2015 16:19, Andrea Mantovani ha scritto:

**Comment by Polpetta** [comment]
Ora ho messo a posto.
