### ISSUE TITLE
Controlli JavaScript su signin

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#40]
Verificare l'accessibilita' in caso javascript sia disattivato su come vengono eseguiti i controlli di consistenza dei dati. 
Problema legato alla issue #27

**Comment by Polpetta** [comment]
@korut94 Ti tiro dentro questa issue per segnalarti che i commit che facciamo in JSDev andrebbero legati qui.

**Comment by Polpetta** [comment]
@massi94 Cambio l'assegnatario a Andrea, in quanto ora e' lui che si deve occupare di fare i controlli da Perl quando JS e' disattivato.
