### ISSUE TITLE
Colori sito non accessibili

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#41]
Facendo i controlli sul sito [www.vischeck.com](www.vischeck.com) e' risultato che non si ha una buona degradazione dei colori
![deuteranope](https://cloud.githubusercontent.com/assets/7117763/12088952/2970df98-b2e0-11e5-9191-28fc686ee9f0.jpg)
![protanope](https://cloud.githubusercontent.com/assets/7117763/12088951/295b7068-b2e0-11e5-91e3-8a47dd5fb29b.jpg)
![tritanope](https://cloud.githubusercontent.com/assets/7117763/12088950/2949d7f4-b2e0-11e5-9a9b-40ef44ea6b28.jpg)
![home](https://cloud.githubusercontent.com/assets/7117763/12088963/30f6b7d8-b2e0-11e5-9f32-c641ea0e95e7.png)

**Comment by WeissL** [comment]
Ok cambio cromatura non è un grosso problema, avete già una preferenza per il colore?

**Comment by Polpetta** [comment]
@WeissL Non ancora, ora vediamo c'è qualche paletta che potrebbe essere applicata! 😊

**Comment by Polpetta** [comment]
@WeissL prendi i colori da qui, che ne dici?  https://www.google.com/design/spec/style/color.html#color-ui-color-application

**Comment by Polpetta** [comment]
Collego la issue al WCAG 2.0 lvl A #43. @WeissL chiudi la issue appena hai fatto.

**Comment by WeissL** [comment]
![vc_a4khkk_sim](https://cloud.githubusercontent.com/assets/15361514/12221312/d31f7996-b795-11e5-8f98-ee187b22a4de.jpg)
![vc_bd1saj_sim](https://cloud.githubusercontent.com/assets/15361514/12221314/d9b29ca2-b795-11e5-97b9-036a8c93ffe0.jpg)
![vc_3rj9b8_sim](https://cloud.githubusercontent.com/assets/15361514/12221315/dba9c90e-b795-11e5-850e-934703c38c61.jpg)

ORIGINALE:
![screenshot from 2016-01-10 12-24-07](https://cloud.githubusercontent.com/assets/15361514/12221316/e580529a-b795-11e5-8a3c-9fa66c14beae.png)

Secondo voi è accettabile

**Comment by Polpetta** [comment]
Ok. Il colore della scritta non andrebbe cambiato @WeissL?

**Comment by WeissL** [comment]
quello del logo dici? volevo cambiarlo all'inizio, poi quando l'ho provato mi ispirava vederlo su sfondo blu... dici che non si legge? i colori per il resto non penso di poterci fare molto di più perchè comunque vada a prendere una paletta di colori quasi sicuramente c'è una base rossa sulle varie tinte

**Comment by Polpetta** [comment]
No per i colori e' ok, intendo per la scritta rossa nel logo. Non si puo' cambiare il colore? Non si intona bene secondo me. Forse con un bianco?

**Comment by WeissL** [comment]
Penso di rovesciare i colori del logo con le figure in bianco e le scritte in nero. Che ne dici? (Scusa mi ero perso sta ripsosta)

**Comment by Polpetta** [comment]
@WeissL se ora i colori del sito sono definitivi, puoi postare qui i risultati di www.vischeck.com? Grazie :blush:

**Comment by WeissL** [comment]
Ecco le foto :)
![screenshot from 2016-01-17 13-05-34](https://cloud.githubusercontent.com/assets/15361514/12377351/44c34584-bd1b-11e5-85c5-0e35efe843ee.png)
![v1](https://cloud.githubusercontent.com/assets/15361514/12377352/46d0f3e4-bd1b-11e5-9eb9-de802ecfd52e.jpg)
![v2](https://cloud.githubusercontent.com/assets/15361514/12377353/482964f6-bd1b-11e5-8a52-6ab193388de5.jpg)
![v3](https://cloud.githubusercontent.com/assets/15361514/12377354/49c79c56-bd1b-11e5-99c8-716e9f0b48ec.jpg)

**Comment by Polpetta** [comment]
ok, questa issue puo' essere chiusa? I colori non cambieranno piu' giusto? :blush:

**Comment by WeissL** [comment]
Spero di no >.< se vi va bene teniamo questi, altrimenti li cambio subito

**Comment by Polpetta** [comment]
No, a me vanno bene questi. @massi94 @korut94 Se nessuno obietta e vi va bene chiudiamo la issue e teniamo questi colori, che finiranno nella relazione con adeguate motivazioni.

**Comment by korut94** [comment]
Chiudi.
