### ISSUE TITLE
Domande da porre alla prof

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#42]
Nel tempo si sono accumulate alcune domande che dobbiamo porre alla prof:
- **HTML**
  - [x] Aggiunta video youtube
  - **Risposta**: Sarebbe meglio usare HTML5. Per l'accessibilitá é possibile usarlo in caso non abbiamo altre possibilitá
- **Perl**
  - [x] Spiegazione del Lock in Perl
  - **Risposta**: Facoltativo per questo progetto
- **JavaScript**
  - [x] Ci sono problemi nel generare XML in JavaScript?
  - **Risposta**: Da evitare in quanto c'é troppo trasferimento di dati, meglio pesare sul server
- **XML**
  - [x] È buona cosa tenere un unico XML Schema e diversi file xml per ogni nodo radice (tende alla veneziana)?
  - **Risposta**: No.

Aggiungete domande modificando a questo post.
Se le domande provengono da issue referenziatele in modo che facciamo prima a rintracciarle dopo.

**Comment by Polpetta** [comment]
Queste sono le risposte date dalla prof.

> Riguardo all'html, quanto giudica accessibile l'aggiunta di video da YouTube o è meglio linkarli semplicemente?

Sinceramente non capisco bene la domanda. Non c’è un youtube è buono/youtube, Y è buono/ Y è cattivo. Si tratta di fare i test di accessibilità sulla pagina e valutare i risultati. Ovviamente i video per essere accessibili dovrebbe fornire alternative testuali o descrizioni audio.

> Riguardo al Perl, dove possiamo trovare della documentazione aggiuntiva relativa ai Lock?

Per il perl, potete guardare il sito perldoc, ma dipende anche dalle impostazioni messe dall’amministratore del server (in questo caso Simion). Mi potete spiegare in dettaglio di cosa avete bisogno?

> Riguardo a JavaScript, ci sono delle problematiche nel generare file XML?

Qui mi spiace ma proprio non capisco la domanda. Problematiche di che tipo?

> Riguardo all'XML, è buona cosa tenere un unico XML Schema e diversi file XML per ogni nodo radice (tende alla veneziana)?

Anche in questo caso la domanda è mal posta. Ovviamente lo schema in genere è una e i file istanza sono tanti, ma la radice in genere è sempre lo stesso tag, indipendentemente dal modello utilizzato. Se avete diversi file con radici diverse, allora bisogna chiedersi se sono contenuti completamente diversi ( e in tal caso meglio schemi diversi) oppure no. Anche in questo caso, un esempio mi aiuterebbe a darvi una risposta piu’ corretta.

Ha chiesto se ne riparliamo in laboratorio. Che dite?

**Comment by korut94** [comment]
@Polpetta Meglio, la trasmissione di informazioni via testuale è uno scoglio di accessibilità. Meglio usare un supporto interattivo audio/video per facilitarle la fruizione dei contenuti.

**Comment by Polpetta** [comment]
Ok, le chiedo se possiamo parlarne prima o dopo il laboratorio! :blush:

**Comment by korut94** [comment]
@Polpetta Durante?

**Comment by Polpetta** [comment]
@korut94 Giusto, la verità sta sempre nel mezzo

**Comment by Polpetta** [comment]
Le riposte sono state date, chiudo.
