### ISSUE TITLE
Pulizia codice e commenti HTML

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#44]
Una volta completato tutto l'HTML, rimuovere commenti per alleggerire i file e renderlo più pulito

**Comment by WeissL** [comment]
Se volete posso toglierli io, anche perchè alcuni non si possono togliere perchè farebbero scoppiare alcuni elementi dello stile (vedi menù, limitazioni tecniche dell'utilizzo di display: inline-block per alcuni browsers)

**Comment by Polpetta** [comment]
@WeissL Si ma va fatta alla fine di tutto, prima di consegnare!:)

**Comment by Polpetta** [comment]
Commenti inutili rimossi, chiudo
