### ISSUE TITLE
Domanda su contenuti extra songManager

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#45]
@massi94 in songManager abbiamo la form scritta in questo modo:

``` html
<form id="insert-song-form" action="../cgi-bin/edit.cgi" method="post">

        <fieldset>

            <input type="text" name="songTitle" id="song-title" />
            <textarea name="songLyrics" id="song-lyrics" rows="80" cols="40"></textarea>
            <textarea name="songExtra" id="song-extra" rows="80" cols="40"></textarea>
            <!-- Le righe e le colonne definite in css? -->
            <input type="submit" value="Conferma" name="action" />
            <input type="submit" value="&#43" name="action" />

        </fieldset>
    </form>
```

Non è meglio che `<textarea name="songExtra" id="song-extra" rows="80" cols="40"></textarea>` sia sostituita con una form? Tanto va inserito solo il link al video di youtube, quindi non serve tanta area editabile!

**Comment by massi94** [comment]
@Polpetta Ma se voglio linkare più versioni presenti su YouTube o voglio aggiungere qualche dettaglio aggiuntivo è meglio una textarea secondo me!

**Comment by Polpetta** [comment]
@massi94 Ok, allora lasciamo textarea!
