### ISSUE TITLE
Domande su 'index.html'

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#5]
A cosa serve? Ci vanno un description ed un title sui meta? MusicCategory = Category? Errore sintassi riga 5 sul segnaposto 'lastNews'.

**Comment by Polpetta** [comment]
Su index vanno semplicemente la barra di ricerca, le ultime news e le categorie delle varie canzoni (potrebbero starci anche quelle più gettonate, generate automaticamente)

Il resto è vuoto. Essendo uno schema LSD non c'è molto altro da aggiungere! :D
