### ISSUE TITLE
H1 H2 e H3 non indentati correttamente

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#50]
"Heading elements must be ordered properly. For example, H2 elements should follow H1 elements, H3 elements should follow H2 elements, etc. Developers should not skip levels or use headings for presentation effects. See http://www.w3.org/TR/WCAG20-TECHS/F43.html (displayed in new window)"

Da modificare index.html.
#43

**Comment by WeissL** [comment]
Mi sembra di averli sistemati tutti per il momento. Ora do un'altra occhiata poi chiudo quest'issue

**Comment by Polpetta** [comment]
@WeissL Ok

**Comment by WeissL** [comment]
Corretto titoli, mi sembra che ora siano tutti apposto
