### ISSUE TITLE
Aggiustare fieldset in tutte le pagine .html

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#51]
The first element inside the `<fieldset>` should be a `<legend>`, which provides a label or instructions for the group. See http://www.w3.org/TR/WCAG20-TECHS/H71.html (displayed in new window)
#43

**Comment by Polpetta** [comment]
@massi94 Questo avevi detto che era un falso positivo di TotalValidator?

**Comment by massi94** [comment]
Da quello che ho capito, secondo me è necessario mettere il `<legend>` quando si utilizzano un insieme di checkbox o radio, o per separare dei form che sono logicamente diversi, nel nostro caso, quindi, si può anche evitare di metterli!

**Comment by Polpetta** [comment]
Ok. Anche perche' noi non abbiamo checkbox mi pare (dovremmo averle eliminate tutte). @massi94 Secondo te questa cosa e' da inserire nella relazione o lasciamo perdere?

**Comment by massi94** [comment]
Secondo me facciamo un TODO sulle cose particolari che abbiamo incontrato mettendo apposto l'accessibilità, e poi inseriamo le più significative

**Comment by Polpetta** [comment]
@massi94 Ok. In ogni caso questa issue e' gia' collegata alla issue sul WCAG 2.0 lvl A, quindi quando andremo a fare la parte di accessibilita' troveremo tutto il necessario.

Quindi chiudo questa issue, mi pare di aver capito che e' tutto risolto qui.
