### ISSUE TITLE
Aggiungere la view per il breadcrumb

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#52]
Manca la definizione di com'è composto l'html per il breadcrumb.

**Comment by Polpetta** [comment]
@korut94 Mmm puoi spiegarti meglio? Che cosa intendi per definizione?

**Comment by korut94** [comment]
La view in html. Tipo:

``` html
<a href=[% breadcrumb %]> [% page %] </a>
```

di un breadcrumb. Di solito c'è il maggiore alla fine.

**Comment by Polpetta** [comment]
@korut94 Ah quindi vuoi che il bradcumb sia una lista di link? O vuoi che il link sia solo all'ultimo cammino?

**Comment by korut94** [comment]
Al contrario, l'ultimo non deve essere proprio un link. E' una lista di link tranne l'ultimo.

Ti consiglio di farlo cosi:
- breadcrumbParent

``` html
<a href="cgi-bin/r.cgi?[% ref_page %]"> [% page %] </a> &gt;
```
- breadcrumbLeaf

``` html
[% page %]
```

ovviamente dentro a div o comunque utilizzabili.

**Comment by korut94** [comment]
Ti consiglio di farlo cosi:
* breadcrumbParent
```html
<a href="cgi-bin/r.cgi?[% ref_page %]"> [% page %] </a> &gt;
```
* breadcrumbLeaf
```html
[% page %]
```
ovviamente dentro a div o comunque utilizzabili.

**Comment by Polpetta** [comment]
@korut94 Agli ordini boss! Appena la faccio legò il commit a questa issue e se è tutto ok la chiudiamo

**Comment by korut94** [comment]
Ma @Polpetta devi aggiungere anche dei div con una classe.

**Comment by Polpetta** [comment]
@korut94 No perché c'è già il DIV breadcumb, quanti ne servono?

**Comment by korut94** [comment]
@korut94 Dove? Nella view page non c'è. Poi ne serve uno per ogni breadcrumb. Guardati quella fatta a laboratorio.

**Comment by Polpetta** [comment]
@korut94 Come nella view page non c'è?? C'è un DIV che segna il breadcumb! Quanti ne servono?

**Comment by korut94** [comment]
C'è questo:

``` html
<p>Ti trovi in: [% breadcumb %]</p>
```

Non serve a molto. Qui dentro ci va un div per ogni parte di breadcrumb.

**Comment by Polpetta** [comment]
@korut94 Ma perché un div? Non ne capisco l'utilità sinceramente! Al massimo uno span

**Comment by korut94** [comment]
Ho guardato le soluzioni della professoresse e hai ragione!

**Comment by Polpetta** [comment]
@korut94 Quindi span o niente?

**Comment by korut94** [comment]
Niente.

**Comment by Polpetta** [comment]
@korut94 Ok, allora chiudi la issue se il breadcumb è ok così

**Comment by korut94** [comment]
Ok!
