### ISSUE TITLE
Pixel Ratio su media queries

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#55]
Il pixel ratio su smartphone è quasi sempre raddoppiato per la visualizzazione di siti. Lei non ne fa conto sulle sue media queries perchè sono ubervecchie... cosa devo fare io? ne tengo conto?

**Comment by korut94** [comment]
@WeissL Usa le sue intanto.

**Comment by WeissL** [comment]
Li metto entrambi, non riesco a testarlo con solo le sue altrimenti

**Comment by korut94** [comment]
@WeissL Va bene. Prova a vedere con dimensioni della finestra del browser consigliate da Marchiori o quello che sai te.
