### ISSUE TITLE
Aggiungere localizzazione inglese ove necessario

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#56]
Nelle pagine html controllare che ogni parola inglese sia segnato dentro span specificando la lingua inglese. Usare:

``` html
<span xml:lang='en'> Parola </span>
```

**Comment by Polpetta** [comment]
@korut94 Legato al WCAG giusto che quando passiamo con l'accessibilità risolviamo la issue

**Comment by korut94** [comment]
Che?

**Comment by Polpetta** [comment]
@korut94 Leggi la premessa della lista WCAG 2.0 Livello A

**Comment by korut94** [comment]
E' inutile questa issue perchè è gia nella lista. La chiudo?

**Comment by Polpetta** [comment]
No, legala alla lista stessa!
E' una cosa che va fatta e legarla alla lista ci ricorda che quando la concludiamo dobbiamo chiudere questa issue. #43

**Comment by korut94** [comment]
Ma se è gia incluso come punto?! E' scrivere due volte la stessa cosa. Ho sbagliato io a aprire questa issue.

**Comment by Polpetta** [comment]
@korut94 Allora cancellala, non chiuderla

**Comment by korut94** [comment]
E come si fa?

**Comment by Polpetta** [comment]
Così
