### ISSUE TITLE
Creare coppia di bottoni modifica e cancellazione

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#57]
Creare la coppia di bottoni nelle seguenti sezioni:
- [x] album
- [x] song
- [x] artist
- [x] article

**Comment by Polpetta** [comment]
@korut94 Guarda come ho pensato di fare la sezione e dimmi se va bene.
La mia idea è che se non si è in modalità amministrativa allora la pagina viene generata senza bottoni. Poi quando si passa in modalità amministrativa, che sia il Perl o il JavaScript i bottoni vengono aggiunti dentro il div.

Il mio dubbio è se anche qui dobbiamo metterci una form. In tal caso che script dovrei chiamare?

**Comment by korut94** [comment]
Va bene. Gli script da chiamare sono la modifica e la cancellazione di quel particolare elemento. La form devi farla solo attorno ai bottoni e magari ci metti qualche campo nascosto per le informazioni essenziali, es. id artista, album, canzone, etc. Ti scrivo la lista degli script:
- modify_album.cgi
- modify_artist.cgi
- modify_song.cgi
- remove_album.cgi
- remove_artist.cgi
- remove_song.cgi

**Comment by korut94** [comment]
Ragazzi non serve più che create delle view sui bottoni di aggiunta e modifica perchè mi baso su editButton.html per crearli. Dovete solo aggiungere si segnaposto [% modifyButton %] e [% removeButton %] dove volete che appaiono.

**Comment by korut94** [comment]
@korut94 Perdono @Polpetta ma non sapevo come unificare i bottoni di modifica e cancellazione in quello di edit.

**Comment by Polpetta** [comment]
Ok, nessun problema.

**Comment by Polpetta** [comment]
Quindi di questa issue cosa dobbiamo farne?
La checkbox e' completa? A che punto siamo?

**Comment by korut94** [comment]
Non create view ma solo inserisce i segnaposto nei posti giusti. Una volta che hai inserito il segnaposto setta la check box corrispondente e quando hai finito chiudi.

**Comment by Polpetta** [comment]
@korut94 Per le categorie manca la view categoryList, la faccio?
Inoltre ho aggiunto i bottoni anche per la lista degli articoli, e' ok? Perche' se si e' necessario che aggiungi anche articoli nella checkbox del commento iniziale.

**Comment by korut94** [comment]
Sarebbe da aggiungere categoryList. Hai fatto bene ad aggiungere i bottoni.

**Comment by Polpetta** [comment]
Ok

**Comment by Polpetta** [comment]
@korut94 @massi94 i bottoni per `song` sono stati creati? Perche' in questo caso questa issue si puo' chiudere.

**Comment by korut94** [comment]
@Polpetta Si si è tutto a posto, chiudi.
