### ISSUE TITLE
Doppio titolo in index? 

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#58]
In index sono indicati due titoli con la stessa dicitura.. (Come dal salumiere) Che faccio? lascio?

**Comment by Polpetta** [comment]
Dici quello con h3 e con h1?

**Comment by WeissL** [comment]
Sì, io li ho configurati entrambi ma suppongo sia solo uno da tenere giusto?

**Comment by Polpetta** [comment]
Si solo uno da tenere in teoria. Non penso che vogliamo due titoli. Ricordati per ogni issue di appiccicarci delle label, milestone e assegnatario, ci permette di indicizzare meglio le issue! :blush:

**Comment by Polpetta** [comment]
@WeissL Se mi dici cosa devo fare mi assegno io la issue dato che si occupa di HTML e ho fatto io la pagina.
Così te la risolvo appena posso e risolvo il problema :blush:

**Comment by WeissL** [comment]
Rimuovi l'h3? :) perchè ho tenuto tutti i primi titoli in h1

**Comment by Polpetta** [comment]
@WeissL Ok!
