### ISSUE TITLE
Mediaqueries per css

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#59]
Apro una nuova issue in merito alle media queries per evidenziare un problema importante sorto durante lo sviluppo. Le media proposte dalla docente non coprono tutte le grandezze, in particolare non viene coperta la fascia 768-1024px... così facendo le modifiche apportate alla parte tablet collassano sullo stile smartphone in quella fascia. Devo aumentare la fascia tablet? la nostra grafica non è così complessa da dover coprire con modifiche importanti anche in quella fascia secondo me

**Comment by Polpetta** [comment]
@WeissL Vuoi che scriva una mail alla prof e sentiamo cosa ci dice? Di solito risponde in una giornata!

**Comment by WeissL** [comment]
Io ho preso come riferimento le sue slide, quella dei css in particolare... nelle ultime 3 slide parla delle media queries e indicava 3 valori per il mobile first. Andrea mi aveva detto di utilizzare quelle indicate dalla prof. in teoria sono quelle no? io sarei propenso di chiudere quella fascia estendendo la query dei tablet, mi sembra la soluzione più ponderata

**Comment by Polpetta** [comment]
@WeissL Ok. Questa cosa bisogna ricordarsi in qualche maniera di segnalarla nella relazione.

**Comment by Polpetta** [comment]
Chiudo in quanto mi pare che il dubbio sia stato chiarito.
