### ISSUE TITLE
Titolo di pagina

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#60]
Stavo guardando il titolo della scheda. Non è meglio invertire le parti? cioè "Passione Karaoke - [%title%]" ? secondo me è più bello piuttosto che come è ora per il motivo che la parte passione karaoke si trova nella stessa posizione. Voi che dite?

**Comment by Polpetta** [comment]
@WeissL Abbiamo fatto questa scelta in base alle slide della prof. @massi94 dovrebbe riuscire a trovarti il punto esatto dove la prof ne parla! 😊

**Comment by korut94** [comment]
@WeissL No perchè il titolo deve andare dal particolare al generale.

**Comment by massi94** [comment]
@Polpetta La prof nelle slide "Principi del web design" dice che i titoli devo o essere "dal particolare al generale e non viceversa"

**Comment by Polpetta** [comment]
@massi94 Ok, mi ricordavo bene allora.

**Comment by Polpetta** [comment]
Chiudo in quanto mi pare che il dubbio sia stato chiarito.

**Comment by korut94** [comment]
@Polpetta Yep
