### ISSUE TITLE
Link assoluti e non relativi su home

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#63]
Ho notato che in home i link sono assoluti e fanno esplodere il sito. sarebbero da cambiare con link relativi

**Comment by korut94** [comment]
@WeissL Dove?

**Comment by Polpetta** [comment]
Se si tratta di HTML lo faccio io.

**Comment by WeissL** [comment]
ho appena verificato. tutti i link della home saltano.

**Comment by Polpetta** [comment]
@WeissL In che branch?

**Comment by WeissL** [comment]
l'html lo avevo preso da htmldev

**Comment by Polpetta** [comment]
Ok. Conta che se stai parlando dei link ai contenuti @korut94 mi aveva informato del fatto che ci potevano essere ancora problemi a riguardo.
Se invece sono i link del menu a essere rotti allora c'e' da fixare

**Comment by WeissL** [comment]
trovato l'inghippo. @korut94 dopo un po' di prove sono arrivato alla conclusione:

Questo è l'indirizzo funzionante
http://127.0.0.1:8080/tecweb/~dpolonio/cgi-bin/r.cgi?section=index
mentre se scrivi questo:
http://127.0.0.1:8080/tecweb/~dpolonio/
è il link che di default perl manda su public_html/index.html

Soluzione possibili a cui ho pensato: 
- fare redirect di index.html sulla path giusta
- tentare di spostare il cgi su public_html, inserendo in index.html uno script che ingloba la prima chiamata a r.cgi (il link giusto, cioè l'index diventerebbe solo un include di questa url) [questa opzione penso sia la più onerosa, non so quanto utile possa essere]
- copia-incollare dei placeholder per sta pagina e inserire i link giusti alle altre pagine
- utilizzare questa pagina come bootscreen, con il logo in grande ed un tasto che rimanda all'index giusta

Che ne dici? Altre opzioni non mi vengono in mente al momento, penso sia una cosa potenzialmente pericolosa giusto?

**Comment by Polpetta** [comment]
@WeissL Secondo me andrebbe bene solo la prima, perché:
-la seconda è sbagliata (non puoi spostare cgi)
-non pensò sia una buona idea
-sarebbe una pugnalata al cuore all'usabilità+accessibilità

**Comment by WeissL** [comment]
èh lo so ma è davvero scomodo come problema questo, contando che il redirect si fa con javascript alla fine ._. non riusciamo a fare redirect lato server in quel caso? con php si riusciva. Con perl mi da questa impressione di una cosa che non si possa fare ._.
Altra opzione:
- c'è la possibilità di mettere un modulo .htaccess?  con quello faremmo oil redirect automatico e sarebbe morto li il problema

**Comment by korut94** [comment]
@WeissL prova a mettere questo frammento nel tuo file html del public_html:

``` html
<meta http-equiv="refresh" content="0; url='link'" />
```

dove 'link' devi scriverlo te e provare finchè non faccia il redirect ad _r.cgi?section=index_

**Comment by WeissL** [comment]
@korut94 non funziona. Ok fa il redirect ma solo con path assoluta (con un URL completo). Poiche noi lo utilizziamo con i ponti ssh non possiamo provedere quale sia sempre l'indirizzo corretto...
PS: ho provato a metterla relativa ma non so ocme mail mi mana in download la lagina r.cgi mettendola così :confused:

**Comment by korut94** [comment]
Allora per il momento non fare nulla. Una volta che consegnamo il progetto la mettiamo e finito.

**Comment by Polpetta** [comment]
@korut94 @WeissL questo problema e' stato risolto?

**Comment by WeissL** [comment]
Se é accettabile la path con "/tecweb/", sibé stata risolta...

**Comment by Polpetta** [comment]
@WeissL Si. Confermo che da ponte SSH e' possibile vedere il CSS. Mi sembra che ci sia anche un problema con la visualizzazione del logo.

Non ho provato tutti i link, ma almeno quelli del contenuto sembravano funzionare. Bisogna sentire @korut94 se tutti i link ora funzionano correttamente.

**Comment by korut94** [comment]
Tutti i link vanno.

**Comment by Polpetta** [comment]
@WeissL il logo confermi che si carica su ramo test? Se si questa issue puo' essere chiusa.

**Comment by WeissL** [comment]
Confermo

**Comment by Polpetta** [comment]
@WeissL Ottimo.
