### ISSUE TITLE
Migliorare l'aggiornamento sito nello spazio web

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#68]
Polpetta fa quello che devi fare.

**Comment by Polpetta** [comment]
Il problema è che travis-ci richiede in ogni caso che prima vengano installate le dipendenze (quindi prima di tutto gli apt-get). Ho provato empiricamente a cambiare l'ordine delle istruzioni, ma dubito fortissimamente che questo faccia cambiare effettivamente l'ordine di esecuzione degli eventi.
