### ISSUE TITLE
Pagine del sito

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#7]
Per facilitarmi il lavoro di composizione pagine, sarebbe comodo per me sapere le pagine principali, i relativi file di partenza e le componenti.
Sarebbe comodo se me lo scriveste cosi come risposta:

_name_page => file( file_c1, file_c2, ..., file_cn );_

e ricorsivamente scrivete le componenti di ogni file come sopra( ricordate la scrittura degli alberi di Filé ).

**Comment by Polpetta** [comment]
Ma le vuoi tutte qui o come commenti su ogni pagina principale?
Il 04/dic/2015 16:02, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Tutte qui sul post di risposta.

**Comment by Polpetta** [comment]
@korut94 Ok!

**Comment by Polpetta** [comment]
Per le mie pagine:
- artist.html(album.html(song.html,_),_)
- artists.html(artistsList.html,)
- index.html(categories.html(category.html,_),_)
- songDescription.html(_,_)
- search.html(searchResult.html,_),_)
- songManager.html(_,_)
- artistManager.html(_,_)
- albumManager.html(albumManagerList.html,_),_)

Mi spiace, sembra che markdown non supporti l'underscore!

**Comment by korut94** [comment]
Come _name_page_ uso direttamente il nome del primo file?

**Comment by Polpetta** [comment]
Si
Il 05/dic/2015 11:04, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Notifa a @massi94: usa lo stesso stile di Davide o il mio.

**Comment by Polpetta** [comment]
E @massi94 quando hai finito chiudi l'issue!!

**Comment by massi94** [comment]
Scusate il ritardo, ecco le pagine:
- article.html(,)
- articles.html(articleList.html,)
- login.html(,)
- signin.html(,)
- userPage.html(adminTools.html,)
- adminTools.html(articleManager.html, artistManager.html, albumManager.html)
- articleManager.html(,)
