### ISSUE TITLE
JavaScript da rimuovere in page.html

### ISSUE THREAD

**Issue by Polpetta** [Hexamini/PassioneKaraoke#70]
Non va bene, fusione tra codice e struttura.

**Comment by WeissL** [comment]
giusto, come gestiamo quegli script? inclusione di più file per ogni specifica od uno script per tutte le cose necessarie?

**Comment by WeissL** [comment]
In che ramo devo fare questa modifica?

**Comment by Polpetta** [comment]
@WeissL Falla pure sul tuo

**Comment by Polpetta** [comment]
@WeissL Mi avevi detto che gli script andavano in public_html/assets, giusto?

**Comment by WeissL** [comment]
ora che assets è stata spostata in data sarebbe giusto farli li penso

**Comment by WeissL** [comment]
Scusate i casini, ho pensato fosse meglio tenerla aperta per capire dove inserire esattamente i javascript
