### ISSUE TITLE
Problema contenuto canzone

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#75]
So che probabilmente sono da rivedere tutti i dati, ma volevo far notare i glifi 
![screenshot from 2016-01-12 21-01-28](https://cloud.githubusercontent.com/assets/15361514/12275369/0977df20-b970-11e5-9408-81329f803a10.png)

succede con tutte le accentate? non prende l'impostazione di charset?

**Comment by korut94** [comment]
E' un problema con tutte le accentate. Si risolverà con la revisione finale.

**Comment by korut94** [comment]
Direi di chiuderla anche.

**Comment by Polpetta** [comment]
Ora come ora non posso vedere lo screenshot (la connessione fa schifo), quindi non ti so dare una mia opinione.
