### ISSUE TITLE
Inserire in userList sulle canzoni piaciute l'id dell'artista e l'id dell'album

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#76]
Il solo id della canzone non basta per disambiguare nel caso ci fossero canzoni con lo stesso nome.

**Comment by korut94** [comment]
Usa questi attributi:
- idArtist
- idAlbum
- idSong

**Comment by massi94** [comment]
Erano già stati inseriti, ma non era stato fatto il merge

**Comment by korut94** [comment]
;)
