### ISSUE TITLE
iframe video youtube

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#78]
Iframe funziona e valida, vanno inseriti su css i valori:
- width
- height
- frameborder="0", che andrebbe sostituito in teoria con border:none

**Comment by WeissL** [comment]
ho inserito i valori per rendere l'iframe fluido con grandezza massima 768px. 
Allego il riferimento:

https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

non ho bene idea di come si possa vedere, in quanto non riesco a caricare un video su quella schermata

**Comment by massi94** [comment]
Mi sono accorto che l'url che va messo nel campo src dell'iframe è diverso dall'url del video di youtube, per quello non si vedeva! adesso ho sistemato, solo che, quando si vuole aggiungere un nuovo video bisogna scrivere solo l'ultima parte del link
Esempio:
Questo è il solito link di youtube:
https://www.youtube.com/watch?v=uezw2XS_va0
e questo è quello che usa iframeç
https://www.youtube.com/embed/uezw2XS_va0

quando inseriamo un video quindi dobbiamo usare scrivere sul database solo l'ultima parte, cioè: uezw2XS_va0

**Comment by WeissL** [comment]
Posso chiudere questa issue?
@massi94
