### ISSUE TITLE
Sostituire i pixel con em

### ISSUE THREAD

**Issue by korut94** [Hexamini/PassioneKaraoke#82]
I pixel sono una forma errata per determinare la misura.

**Comment by WeissL** [comment]
Posso farlo senza problemi per i font... Dicevi quello tu? perchè farlo per margini, padding e grandezze sarebbe impossibile... si snutellerebbe sempre tutto... in più se uno aumentasse il font con il browser scoppierebbe tutto...

**Comment by korut94** [comment]
@WeissL I pixel non sono mai da usare perchè non garantiscono l'adattamento del sito web nel caso l'utente impostasse un font superiore a quello che noi abbiamo stabilito. E' un discorso di accessibilità.

**Comment by korut94** [comment]
@WeissL Fallo anche una merda semplice ma non puoi usare i pixel.

**Comment by WeissL** [comment]
Da quello che vedo si utilizzerebbe rem ma non è supportato da browsers vecchi.... il fatto è che cambiando solo il font diventerebbe elastico e tutto andrebbe bene, perchè la grafica scalerebbe bene... se metto tutto il sito in em se ne va a puttane tutto il layout, con bande orizzontali di scorrimento e cose varie se uno aumenta il font

**Comment by Polpetta** [comment]
@WeissL Il problema è che la prof vuole così, c'è poco da fare

**Comment by korut94** [comment]
In se ha detto che è un discorso di proporzioni. Con i pixel non si ha questo effetto.
