### ISSUE TITLE
Sistemati Image of Text e Resize Text

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#87]
Per image of Text non c'è nulla da segnalare in quanto l'unica immagine che contiene testo è il logotipo che è ammesso.

Per il resize del testo ho fatto entrambe le prove: 
- la prova meno significativa è lo zoom del brawser. non sono state registrate anomalie di nessun tipo
- la prova più significativa è stata con un tool per ingrandire solo il testo lasciando invariata la grandezza della schermata: anche in questo caso il sito si presenta leggibile senza nessun problema
#48

**Comment by WeissL** [comment]
Allego il link del tool:

https://github.com/lihanli/chrome-text-only-zoom

**Comment by Polpetta** [comment]
@WeissL Bene cosi', ma ricordati nelle issue assegnare le giuste labels, la milestone e l'assegnatario corrente. In questa maniera rimane tutto piu' organizzato, e prima della consegna abbiamo la possibilita' di controllare che tutti i _todo_ e tutti i _memo_ siano stati fatti!! :blush:
