### ISSUE TITLE
Colori sito per leggibilità e contrasto sistemati

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#88]
Allego tutti i report per la sistemazione di questo punto:

**Punto di interesse: Voci del menu**
![screenshot from 2016-01-30 00-12-40](https://cloud.githubusercontent.com/assets/15361514/12690791/514c579e-c6e6-11e5-81ac-c8155453414f.png)

Risultato:
![screenshot from 2016-01-30 00-18-01](https://cloud.githubusercontent.com/assets/15361514/12690883/f9005ddc-c6e6-11e5-81d3-9cce513c9ebd.png)

Indice accettato dal livello AAA di WCAG

Risultato peggiore per il menu è in caso di hover:
![screenshot from 2016-01-30 00-19-11](https://cloud.githubusercontent.com/assets/15361514/12690901/218960fa-c6e7-11e5-98f1-a06122359220.png)

In questo caso l'indice è:
![screenshot from 2016-01-30 00-20-35](https://cloud.githubusercontent.com/assets/15361514/12690914/5171a21e-c6e7-11e5-8bdc-b8fafce1b048.png)

Anche in questo caso la sezione risulta accettabile per il livello AAA in quanto l'indice è accettabile per "large text" e l'elemento ha dimensione 1.125em (18px normal size)

**Punto di interesse: homepage**
Nell'homepage sono presenti i box per articoli e canzoni
![screenshot from 2016-01-30 00-28-47](https://cloud.githubusercontent.com/assets/15361514/12691013/749af44c-c6e8-11e5-987e-f7b4599e7668.png)
Indice:
![screenshot from 2016-01-30 00-29-48](https://cloud.githubusercontent.com/assets/15361514/12691029/98575466-c6e8-11e5-8489-9c4366cf8df4.png)

**Punto di interesse: pagina artisti**
In questa pagina il punto a rischio sono le scritte dentro ai box degli artisti
![screenshot from 2016-01-30 00-31-12](https://cloud.githubusercontent.com/assets/15361514/12691050/d11495b6-c6e8-11e5-9c1f-47d8c50f0da7.png)

L'indice per questa sezione è:
![screenshot from 2016-01-30 00-32-12](https://cloud.githubusercontent.com/assets/15361514/12691065/f05446b0-c6e8-11e5-9f4b-ce4856031ee7.png)

**Punto di interesse: box degli articoli**
Indice di contrasto per i box degli articoli
![screenshot from 2016-01-30 00-33-13](https://cloud.githubusercontent.com/assets/15361514/12691086/14e32dd4-c6e9-11e5-9385-65c373681065.png)

L'indice di contrasto tra il testo e lo sfondo è:
![screenshot from 2016-01-30 00-34-19](https://cloud.githubusercontent.com/assets/15361514/12691105/3c17f83a-c6e9-11e5-84f0-a7cce55c6dc1.png)

**Punto di interesse: testo generico sulle descrizioni e sugli articoli**
In questo caso si tratta del contrasto tra lo sfondo e il testo degli articoli
![screenshot from 2016-01-30 00-35-40](https://cloud.githubusercontent.com/assets/15361514/12691140/6a3cb0b6-c6e9-11e5-896a-a5aca77c6ac9.png)

Il colore più a basso contrasto è quello del testo che presenta un indice di:
![screenshot from 2016-01-30 00-36-33](https://cloud.githubusercontent.com/assets/15361514/12691156/8961a91a-c6e9-11e5-9d1c-6fb16329902d.png)
#48

**Comment by Polpetta** [comment]
@WeissL grazie, ottimo lavoro! :+1: :blush:

**Comment by WeissL** [comment]
Se volete modificare i colori ditemi che aggiornò anche la issue

**Comment by Polpetta** [comment]
@WeissL No, per il momento va bene cosi'! :blush:

**Comment by Polpetta** [comment]
Commento questa issue come memo per segnalare che questa parte è stata scritta nella relazione.

Il commit in questione è il 4555510
