### ISSUE TITLE
Controllo TotalValidator

### ISSUE THREAD

**Issue by massi94** [Hexamini/PassioneKaraoke#89]
Ho fatto i test con total validator delle pagine, e ho trovato questi problemi:
- Su tutte le pagine:
  - [x] Warning: Unrecognised value for the 'name' attribute: `<meta name="title" content="Pagina Utente di fabio Passione Karaoke"/>`
  - [x] Warning: Unrecognised value for the 'name' attribute: `<meta name="language" content="italian it"/>`
- Artitsti:
  - Sezione amministrativa:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that group
    - [x] Error: Anchor 'name' and 'id' attributes must be unique in the same document: See matching tag(s) on line(s) (form edit mode)
  - Aggiunta artista:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that groug 
  - Pagina artista:
    - [x] Error: Anchor 'name' and 'id' attributes must be unique in the same document: See matching tag(s) on line(s) (form edit mode)
    - [x] Error: The 'src' attribute does not have a valid value: It cannot be a blank value:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that group
  - Aggiungi Album:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that group
  - Aggiungi Canzone:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that group
- Articoli:
  - Aggiungi Articolo:
    - [x] Warning: Each `<fieldset>` should have a <legend> element that includes a description of that group

**Comment by Polpetta** [comment]
@massi94 Segno gia' quelle delle filedset perche' avevamo detto che erano falsi positivi!

**Comment by Polpetta** [comment]
Segnalo i seguenti link utili alla discussione sui due warning:
- https://www.w3.org/TR/html5/document-metadata.html#the-meta-element
- https://developer.mozilla.org/it/docs/Web/HTML/Element/meta#attr-name

**Comment by massi94** [comment]
Falso positivo
