### ISSUE TITLE
Immagini talloncini w3c

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#98]
Siamo sicuri che vadano bene? perchè dovrebbero avere un link che rimandano al certificato di validità, dovrebbero essere generati da w3c dal loro sito per essere inglobati

**Comment by Polpetta** [comment]
@WeissL Tranne il talloncino dell'html5 tutti gli altri sino stati presi dal validatore (anche html5 valida ma non ti da il talloncino), ma gli abbiamo tolto il link perché anche la prof nel suo sito ha fatto così! Decisione presa con @massi94
