### ISSUE TITLE
Form per stile di stampa

### ISSUE THREAD

**Issue by WeissL** [Hexamini/PassioneKaraoke#99]
Devono essere ricreati anche tutti i form per lo stile di stampa? 
Non ha molto senso rifarli per la stampa, in teoria già di suo si tolgono i colori, la barra di navigazione è assente e il color del testo è nero (#000).

@Polpetta @korut94 @massi94

**Comment by Polpetta** [comment]
@WeissL Per me non hanno senso. Sentiamo cosa dicono gli altri

**Comment by WeissL** [comment]
@korut94 @massi94 Cosa dite? chiudo?

**Comment by korut94** [comment]
Non l'ho mai visto.

**Comment by Polpetta** [comment]
@WeissL io ho questo risultato con il css di stampa:
![immagine](https://cloud.githubusercontent.com/assets/5928183/12818601/d454fb26-cb57-11e5-8ddf-9fd0931cf2cb.png)

E' normale che il riquadro vada fuori dalla pagina a sinistra? :blush:

**Comment by WeissL** [comment]
opera di merda ... ora faccio uno shortcut per evitare quei problemi

**Comment by Polpetta** [comment]
@WeissL Ovvero?

**Comment by WeissL** [comment]
quello che ho appena pushato XD

**Comment by Polpetta** [comment]
@WeissL Ok, adesso vedo il commit 2f2f14d

**Comment by Polpetta** [comment]
@WeissL chiudo in quanto sembra andare bene.
